# Generated by Django 5.2.4 on 2025-07-05 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_alter_products_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
